### ISSUE TITLE
Choose toolkit (lwjgl?)

### ISSUE THREAD

**Issue by ArtemPopof** [OpenGameOrg/GrandOpenGame#3]
LWJG can be a good choice, because it provides a lower-level access to the OpenGL and Vulkan with ability to tune engine better

cons is slower progress of development

**Comment by ArtemPopof** [comment]
LWJG seems to be too low-level for the moment. Switched to the jMonkeyEngine, anyway we can rollback to the low level tools in the future.

**Comment by JorgenPo** [comment]
You should probably use UE or Unity, the support java out of the box and are better
